// Regenerates the game-data seed migration from data/*.ts so the database and
// the app always share one catalog. Run: npm run db:seed:generate
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { COMPONENTS } from "../data/components";
import { ACHIEVEMENTS } from "../data/achievements";
import { CHALLENGE_TEMPLATES } from "../data/challenges";

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const components = COMPONENTS.map(
  (c) => `  (${q(c.id)}, ${q(c.name)}, ${q(c.category)}, ${q(c.rarity)}, ${c.price}, ${c.performance}, ${c.power}, ${q(c.description)}, ${j(c.metadata)})`,
).join(",\n");

const achievements = ACHIEVEMENTS.map(
  (a) => `  (${q(a.id)}, ${q(a.name)}, ${q(a.description)}, ${q(a.icon)}, ${q(a.requirementType)}, ${a.requirementValue})`,
).join(",\n");

const templates = CHALLENGE_TEMPLATES.map((t, i) => `  (${i}, ${q(t.title)}, ${q(t.description)}, ${j(t.rules)})`).join(",\n");

const sql = `-- GENERATED by scripts/generate-seed.ts — do not edit by hand.
-- Fictional RH PC LAB game data (not official Computers RH items).

insert into public.components (id, name, category, rarity, price, performance, power, description, metadata) values
${components}
on conflict (id) do update set
  name = excluded.name, category = excluded.category, rarity = excluded.rarity, price = excluded.price,
  performance = excluded.performance, power = excluded.power, description = excluded.description, metadata = excluded.metadata;

insert into public.achievements (id, name, description, icon, requirement_type, requirement_value) values
${achievements}
on conflict (id) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  requirement_type = excluded.requirement_type, requirement_value = excluded.requirement_value;

-- One challenge per UTC day, rotating through the templates by day index
-- (matches challengeForDate() in lib/pc-engine/challenges.ts).
with templates (idx, title, description, rules) as (values
${templates}
)
insert into public.daily_challenges (id, title, description, rules, start_date, end_date)
select to_char(d, 'YYYY-MM-DD'), t.title, t.description, t.rules, d::date, d::date
from generate_series(date '2026-01-01', date '2028-12-31', interval '1 day') as d
join templates t on t.idx = ((d::date - date '1970-01-01') % ${CHALLENGE_TEMPLATES.length})
on conflict (id) do nothing;
`;

const out = join(import.meta.dirname, "../supabase/migrations/20261006000100_seed_game_data.sql");
writeFileSync(out, sql);
console.log(`wrote ${out} (${COMPONENTS.length} components, ${ACHIEVEMENTS.length} achievements, ${CHALLENGE_TEMPLATES.length} challenge templates)`);
