-- GENERATED by scripts/generate-seed.ts — do not edit by hand.
-- Fictional RH PC LAB game data (not official Computers RH items).

insert into public.components (id, name, category, rarity, price, performance, power, description, metadata) values
  ('case-retrobox', 'RetroBox', 'case', 'COMMON', 59, 40, 0, 'Beige, boxy and proud. Smells faintly of floppy disks.', '{"size":"MID","formFactors":["ITX","MATX"],"maxGpuLength":260,"maxCoolerHeight":150,"maxRadiator":0,"airflow":45,"color":"#E8D9B8","trim":"#B9A57E","glass":false,"retro":true}'::jsonb),
  ('case-nightbox', 'NightBox', 'case', 'UNCOMMON', 99, 60, 0, 'Matte midnight mid-tower with a tempered glass side panel.', '{"size":"MID","formFactors":["ITX","MATX","ATX"],"maxGpuLength":330,"maxCoolerHeight":165,"maxRadiator":240,"airflow":65,"color":"#1B2247","trim":"#3B4680","glass":true}'::jsonb),
  ('case-pocketbox', 'PocketBox Mini', 'case', 'RARE', 149, 66, 0, 'Tiny ITX cube. Fits in a backpack, fights like a tower.', '{"size":"MINI","formFactors":["ITX"],"maxGpuLength":300,"maxCoolerHeight":70,"maxRadiator":240,"airflow":55,"color":"#F4D4D1","trim":"#C99BA8","glass":true}'::jsonb),
  ('case-aquaglass', 'AquaGlass', 'case', 'EPIC', 189, 78, 0, 'Dual-chamber fishbowl with panoramic glass. Show off everything.', '{"size":"MID","formFactors":["ITX","MATX","ATX"],"maxGpuLength":360,"maxCoolerHeight":170,"maxRadiator":360,"airflow":75,"color":"#DDE6F7","trim":"#7E8FC4","glass":true}'::jsonb),
  ('case-titan', 'Titan Tower', 'case', 'LEGENDARY', 289, 88, 0, 'Full tower with room for EATX, giant GPUs and a 420mm radiator.', '{"size":"FULL","formFactors":["ITX","MATX","ATX","EATX"],"maxGpuLength":420,"maxCoolerHeight":185,"maxRadiator":420,"airflow":85,"color":"#2B2152","trim":"#6D5A9E","glass":true}'::jsonb),
  ('case-prism', 'Prism Ω', 'case', 'MYTHIC', 499, 97, 0, 'Machined crystal frame. Rumoured to hum in perfect fifths.', '{"size":"FULL","formFactors":["ITX","MATX","ATX","EATX"],"maxGpuLength":450,"maxCoolerHeight":190,"maxRadiator":480,"airflow":95,"color":"#F7F1FF","trim":"#FF7EB6","glass":true}'::jsonb),
  ('cpu-retrochip-486', 'RetroChip 486DX', 'cpu', 'COMMON', 49, 22, 45, 'Turbo button included. Runs everything from 1994 flawlessly.', '{"socket":"LEGACY-4","cores":2,"boostGhz":2.4}'::jsonb),
  ('cpu-rh-core-i3', 'RH-Core S3', 'cpu', 'COMMON', 119, 38, 65, 'Honest four-core starter chip. Great first rig energy.', '{"socket":"RH-1","cores":4,"boostGhz":4.2}'::jsonb),
  ('cpu-novachip-5600', 'NovaChip 5600', 'cpu', 'UNCOMMON', 189, 55, 65, 'Six efficient cores. The budget gamer''s best friend.', '{"socket":"NV-5","cores":6,"boostGhz":4.6}'::jsonb),
  ('cpu-rh-core-m7', 'RH-Core M7', 'cpu', 'RARE', 339, 72, 125, 'Twelve cores of balanced muscle for gaming and streaming.', '{"socket":"RH-1","cores":12,"boostGhz":5.1}'::jsonb),
  ('cpu-novachip-7950x', 'NovaChip 7950X', 'cpu', 'EPIC', 529, 84, 170, 'Sixteen cores. Compiles your code before you finish typing it.', '{"socket":"NV-5","cores":16,"boostGhz":5.7}'::jsonb),
  ('cpu-rh-core-x9', 'RH-Core X9', 'cpu', 'LEGENDARY', 689, 93, 200, 'Flagship 24-core monster. Bring serious cooling.', '{"socket":"RH-1","cores":24,"boostGhz":6}'::jsonb),
  ('cpu-quantum-q1', 'Quantum Q-1 Singularity', 'cpu', 'MYTHIC', 1199, 99, 250, 'Exists in every clock state at once. Lab-grade cooling required.', '{"socket":"NV-5","cores":32,"boostGhz":6.6}'::jsonb),
  ('gpu-pixelforce-1650', 'PixelForce 1650 Lite', 'gpu', 'COMMON', 149, 30, 75, 'Slot-powered little card. Esports at 1080p, no problem.', '{"length":170,"vram":4,"fans":1}'::jsonb),
  ('gpu-pixelforce-3060', 'PixelForce 3060', 'gpu', 'UNCOMMON', 299, 48, 170, 'The people''s GPU. Solid 1080p with room to breathe.', '{"length":240,"vram":12,"fans":2}'::jsonb),
  ('gpu-radiant-6700', 'Radiant RX 6700', 'gpu', 'UNCOMMON', 359, 55, 220, 'Warm red glow, cool 1440p frames.', '{"length":270,"vram":12,"fans":2}'::jsonb),
  ('gpu-pixelforce-7800', 'PixelForce 7800', 'gpu', 'RARE', 599, 70, 285, 'High-refresh 1440p sweet spot with ray-traced puddles.', '{"length":300,"vram":16,"fans":3}'::jsonb),
  ('gpu-radiant-7900', 'Radiant RX 7900', 'gpu', 'EPIC', 849, 82, 320, '24GB of VRAM. Texture packs fear it.', '{"length":320,"vram":24,"fans":3}'::jsonb),
  ('gpu-pixelforce-8080ti', 'PixelForce 8080 Ti', 'gpu', 'EPIC', 1049, 86, 350, '4K-ready triple-fan bruiser with a backplate you can see from space.', '{"length":335,"vram":20,"fans":3}'::jsonb),
  ('gpu-pixelforce-9090', 'PixelForce 9090', 'gpu', 'LEGENDARY', 1799, 95, 420, 'The king of frames. Needs a big case and a bigger PSU.', '{"length":350,"vram":32,"fans":3}'::jsonb),
  ('gpu-neon-titan', 'Neon Titan Ω', 'gpu', 'MYTHIC', 2599, 100, 520, 'Renders reality at 8K. Only full towers can contain it.', '{"length":380,"vram":48,"fans":4}'::jsonb),
  ('mobo-retroboard-4l', 'RetroBoard 4L', 'motherboard', 'COMMON', 69, 30, 30, 'Legacy micro-ATX board. DDR4 only, no M.2 slots.', '{"socket":"LEGACY-4","formFactor":"MATX","ramType":"DDR4","maxRamGb":32,"m2Slots":0}'::jsonb),
  ('mobo-pixelboard-b', 'PixelBoard B', 'motherboard', 'COMMON', 109, 50, 40, 'No-frills micro-ATX board for RH-Core chips.', '{"socket":"RH-1","formFactor":"MATX","ramType":"DDR4","maxRamGb":64,"m2Slots":1}'::jsonb),
  ('mobo-novaboard-mini', 'NovaBoard Mini', 'motherboard', 'RARE', 219, 70, 45, 'Mini-ITX powerhouse for NovaChips. Small-form-factor approved.', '{"socket":"NV-5","formFactor":"ITX","ramType":"DDR5","maxRamGb":64,"m2Slots":2}'::jsonb),
  ('mobo-pixelboard-x', 'PixelBoard X', 'motherboard', 'EPIC', 299, 82, 55, 'Full ATX DDR5 board with chunky VRMs for RH-Core flagships.', '{"socket":"RH-1","formFactor":"ATX","ramType":"DDR5","maxRamGb":128,"m2Slots":3}'::jsonb),
  ('mobo-novaboard-pro', 'NovaBoard Pro X', 'motherboard', 'EPIC', 329, 84, 55, 'ATX DDR5 board tuned for high-core NovaChips.', '{"socket":"NV-5","formFactor":"ATX","ramType":"DDR5","maxRamGb":256,"m2Slots":3}'::jsonb),
  ('mobo-omniboard', 'OmniBoard Extreme', 'motherboard', 'LEGENDARY', 599, 95, 65, 'Extended-ATX flagship with four M.2 slots and a tiny OLED.', '{"socket":"RH-1","formFactor":"EATX","ramType":"DDR5","maxRamGb":256,"m2Slots":4}'::jsonb),
  ('ram-basic-8', 'BasicRAM 8', 'ram', 'COMMON', 25, 28, 5, '8GB DDR4-2666. It boots. Mostly.', '{"ramType":"DDR4","capacityGb":8,"speed":2666,"sticks":1}'::jsonb),
  ('ram-cloud-16', 'CloudRAM 16', 'ram', 'UNCOMMON', 49, 48, 6, '16GB DDR4-3200 dual-channel kit. The safe pick.', '{"ramType":"DDR4","capacityGb":16,"speed":3200,"sticks":2}'::jsonb),
  ('ram-cloud-32', 'CloudRAM 32', 'ram', 'RARE', 109, 68, 8, '32GB DDR5-5600 with soft mint heat spreaders.', '{"ramType":"DDR5","capacityGb":32,"speed":5600,"sticks":2}'::jsonb),
  ('ram-cloud-64', 'CloudRAM 64', 'ram', 'EPIC', 219, 82, 10, '64GB DDR5-6000. Open every tab. All of them.', '{"ramType":"DDR5","capacityGb":64,"speed":6000,"sticks":2}'::jsonb),
  ('ram-quantum-128', 'QuantumRAM 128', 'ram', 'LEGENDARY', 449, 92, 14, '128GB DDR5-6400 quad kit with RGB light bars.', '{"ramType":"DDR5","capacityGb":128,"speed":6400,"sticks":4}'::jsonb),
  ('ram-hyper-256', 'HyperRAM 256 Ω', 'ram', 'MYTHIC', 999, 100, 18, '256GB DDR5-7200. Remembers things you forgot.', '{"ramType":"DDR5","capacityGb":256,"speed":7200,"sticks":4}'::jsonb),
  ('ssd-spindisk-1tb', 'SpinDisk 1TB', 'storage', 'COMMON', 39, 22, 8, 'Spinning rust. Listen closely and you can hear it think.', '{"interface":"SATA","capacityTb":1,"readMbs":160}'::jsonb),
  ('ssd-bytedrive-1tb', 'ByteDrive 1TB SATA', 'storage', 'UNCOMMON', 59, 45, 4, 'Reliable SATA SSD. Instant upgrade from spinning disks.', '{"interface":"SATA","capacityTb":1,"readMbs":550}'::jsonb),
  ('ssd-bytedrive-2tb', 'ByteDrive 2TB', 'storage', 'RARE', 129, 68, 5, '2TB NVMe Gen4. Load screens? Never heard of them.', '{"interface":"NVME","capacityTb":2,"readMbs":7000}'::jsonb),
  ('ssd-bytedrive-4tb', 'ByteDrive 4TB', 'storage', 'EPIC', 259, 82, 6, '4TB NVMe Gen4 for your entire game library.', '{"interface":"NVME","capacityTb":4,"readMbs":7400}'::jsonb),
  ('ssd-warpdrive-8tb', 'WarpDrive 8TB', 'storage', 'LEGENDARY', 649, 92, 8, '8TB NVMe Gen5 with a heatsink shaped like a tiny spaceship.', '{"interface":"NVME","capacityTb":8,"readMbs":12400}'::jsonb),
  ('ssd-infinity-vault', 'Infinity Vault 16TB', 'storage', 'MYTHIC', 1299, 100, 10, '16TB of Gen5 bliss. Holds every save file you''ve ever made.', '{"interface":"NVME","capacityTb":16,"readMbs":14800}'::jsonb),
  ('psu-powerunit-450', 'PowerUnit 450', 'psu', 'COMMON', 45, 35, 0, '450W Bronze. Enough for office rigs and small dreams.', '{"wattage":450,"efficiency":"BRONZE","modular":false}'::jsonb),
  ('psu-powerunit-650', 'PowerUnit 650', 'psu', 'UNCOMMON', 79, 55, 0, '650W Gold. The mid-range workhorse.', '{"wattage":650,"efficiency":"GOLD","modular":false}'::jsonb),
  ('psu-powerunit-850', 'PowerUnit 850', 'psu', 'RARE', 129, 70, 0, '850W Gold, fully modular. Clean cables, clean conscience.', '{"wattage":850,"efficiency":"GOLD","modular":true}'::jsonb),
  ('psu-powerunit-1000', 'PowerUnit 1000', 'psu', 'EPIC', 199, 82, 0, '1000W Platinum. Feeds high-end GPUs without breaking a sweat.', '{"wattage":1000,"efficiency":"PLATINUM","modular":true}'::jsonb),
  ('psu-powerunit-1200', 'PowerUnit 1200', 'psu', 'LEGENDARY', 299, 92, 0, '1200W Titanium. Whisper quiet, absurdly efficient.', '{"wattage":1200,"efficiency":"TITANIUM","modular":true}'::jsonb),
  ('psu-reactorcore-1600', 'ReactorCore 1600', 'psu', 'MYTHIC', 549, 100, 0, '1600W Titanium. Could probably power the whole lab.', '{"wattage":1600,"efficiency":"TITANIUM","modular":true}'::jsonb),
  ('cool-stockfan', 'StockFan 65', 'cooling', 'COMMON', 15, 30, 3, 'Low-profile box cooler. Fine for 65W chips, sad for anything more.', '{"type":"AIR","sockets":["RH-1","NV-5","LEGACY-4"],"maxTdp":65,"height":55}'::jsonb),
  ('cool-turbocooler', 'TurboCooler', 'cooling', 'UNCOMMON', 39, 55, 4, 'Single-tower air cooler with a cheerful 120mm fan.', '{"type":"AIR","sockets":["RH-1","NV-5","LEGACY-4"],"maxTdp":150,"height":155}'::jsonb),
  ('cool-frosttower', 'FrostTower Dual', 'cooling', 'RARE', 89, 72, 6, 'Dual-tower air beast. Modern sockets only.', '{"type":"AIR","sockets":["RH-1","NV-5"],"maxTdp":220,"height":168}'::jsonb),
  ('cool-iceloop-240', 'IceLoop 240', 'cooling', 'EPIC', 129, 80, 8, '240mm AIO liquid cooler with a glowing pump cap.', '{"type":"AIO","sockets":["RH-1","NV-5"],"maxTdp":250,"radiator":240}'::jsonb),
  ('cool-iceloop-360', 'IceLoop 360', 'cooling', 'LEGENDARY', 189, 90, 12, '360mm AIO. Keeps flagship CPUs frosty under any load.', '{"type":"AIO","sockets":["RH-1","NV-5"],"maxTdp":320,"radiator":360}'::jsonb),
  ('cool-cryocore', 'CryoCore Custom Loop', 'cooling', 'MYTHIC', 499, 100, 20, 'Hand-bent hardline loop with coloured coolant. Pure art.', '{"type":"CUSTOM","sockets":["RH-1","NV-5"],"maxTdp":420,"radiator":360}'::jsonb),
  ('mon-office-22', 'OfficeView 22', 'monitor', 'COMMON', 99, 25, 0, '22" 1080p 60Hz. Spreadsheets have never looked so average.', '{"sizeIn":22,"resolution":"1080P","refreshHz":60}'::jsonb),
  ('mon-retrotube-17', 'RetroTube CRT 17', 'monitor', 'UNCOMMON', 129, 40, 0, '17" CRT with real scanlines and zero input lag.', '{"sizeIn":17,"resolution":"1024×768","refreshHz":85,"crt":true}'::jsonb),
  ('mon-gamer-24', 'SwiftPixel 24', 'monitor', 'UNCOMMON', 179, 50, 0, '24" 1080p 165Hz. Competitive shooters, meet your match.', '{"sizeIn":24,"resolution":"1080P","refreshHz":165}'::jsonb),
  ('mon-pixelview-27', 'PixelView 27', 'monitor', 'RARE', 349, 72, 0, '27" 1440p 240Hz OLED. Inky blacks, buttery motion.', '{"sizeIn":27,"resolution":"1440P","refreshHz":240}'::jsonb),
  ('mon-pixelview-32', 'PixelView 32 4K', 'monitor', 'EPIC', 699, 86, 0, '32" 4K 144Hz. Every pixel you could ever want.', '{"sizeIn":32,"resolution":"4K","refreshHz":144}'::jsonb),
  ('mon-horizon-49', 'Horizon 49 Ultrawide', 'monitor', 'LEGENDARY', 1199, 95, 0, '49" super-ultrawide 240Hz. Peripheral vision: maxed.', '{"sizeIn":49,"resolution":"5120×1440","refreshHz":240,"ultrawide":true}'::jsonb),
  ('kb-membrane', 'Membrane Basic', 'keyboard', 'COMMON', 15, 20, 1, 'Mushy but loyal. Came free with something, probably.', '{"layout":"FULL","switches":"Membrane","rgb":false}'::jsonb),
  ('kb-clackboard', 'ClackBoard TKL', 'keyboard', 'UNCOMMON', 69, 50, 2, 'Tenkeyless mechanical with clicky blue switches. Sorry, roommates.', '{"layout":"TKL","switches":"Clicky Blue","rgb":false}'::jsonb),
  ('kb-pixelkeys-60', 'PixelKeys 60', 'keyboard', 'RARE', 119, 68, 3, 'Compact 60% with per-key RGB and pastel keycaps.', '{"layout":"60%","switches":"Linear Mint","rgb":true}'::jsonb),
  ('kb-typewriter', 'TypeWriter Retro', 'keyboard', 'EPIC', 179, 78, 2, 'Round keycaps, brass accents, thocky tactile switches.', '{"layout":"TKL","switches":"Tactile Thock","rgb":false,"retro":true}'::jsonb),
  ('kb-aurora', 'AuroraBoard Pro', 'keyboard', 'LEGENDARY', 249, 92, 4, 'Full-size aluminium board with a light-bar that paints the desk.', '{"layout":"FULL","switches":"Magnetic Hall","rgb":true}'::jsonb),
  ('mouse-basicclick', 'BasicClick', 'mouse', 'COMMON', 9, 20, 1, 'Two buttons and a wheel. What more could you need?', '{"dpi":1000,"weightG":95,"wireless":false,"rgb":false}'::jsonb),
  ('mouse-glide', 'GlideMouse', 'mouse', 'UNCOMMON', 39, 50, 1, 'Comfy ergonomic shape with PTFE feet.', '{"dpi":8000,"weightG":80,"wireless":false,"rgb":false}'::jsonb),
  ('mouse-pixelmouse', 'PixelMouse Pro', 'mouse', 'RARE', 79, 70, 2, 'Esports shape, RGB logo, flawless sensor.', '{"dpi":26000,"weightG":63,"wireless":false,"rgb":true}'::jsonb),
  ('mouse-featherlite', 'FeatherLite 49', 'mouse', 'EPIC', 129, 84, 1, '49 grams wireless. Your wrist will thank you.', '{"dpi":30000,"weightG":49,"wireless":true,"rgb":false}'::jsonb),
  ('mouse-zenith', 'Zenith Wireless', 'mouse', 'LEGENDARY', 179, 94, 2, '8K polling, magnetic charging dock, glowing scroll wheel.', '{"dpi":36000,"weightG":55,"wireless":true,"rgb":true}'::jsonb)
on conflict (id) do update set
  name = excluded.name, category = excluded.category, rarity = excluded.rarity, price = excluded.price,
  performance = excluded.performance, power = excluded.power, description = excluded.description, metadata = excluded.metadata;

insert into public.achievements (id, name, description, icon, requirement_type, requirement_value) values
  ('first-boot', 'FIRST BOOT', 'Create your first PC.', 'power', 'builds_count', 1),
  ('hardware-engineer', 'HARDWARE ENGINEER', 'Create 5 PCs.', 'wrench', 'builds_count', 5),
  ('maxed-out', 'MAXED OUT', 'Reach a 95+ score.', 'bolt', 'best_score', 95),
  ('legendary', 'LEGENDARY', 'Build a Legendary PC.', 'crown', 'min_rarity', 4),
  ('mythic', 'MYTHIC', 'Build a Mythic PC.', 'gem', 'min_rarity', 5),
  ('collector', 'COLLECTOR', 'Save 10 builds.', 'floppy', 'builds_count', 10),
  ('community-builder', 'COMMUNITY BUILDER', 'Receive 50 likes.', 'heart', 'likes_received', 50),
  ('speedrunner', 'SPEEDRUNNER', 'Complete a PC in under 2 minutes.', 'clock', 'speedrun', 120)
on conflict (id) do update set
  name = excluded.name, description = excluded.description, icon = excluded.icon,
  requirement_type = excluded.requirement_type, requirement_value = excluded.requirement_value;

-- One challenge per UTC day, rotating through the templates by day index
-- (matches challengeForDate() in lib/pc-engine/challenges.ts).
with templates (idx, title, description, rules) as (values
  (0, 'BUILD UNDER $2,000', 'Squeeze the most score out of a tight budget.', '{"maxBudget":2000,"minRamGb":16,"requiredCategories":["gpu"]}'::jsonb),
  (1, 'MAXIMUM PERFORMANCE', 'No budget limit. Highest score wins.', '{}'::jsonb),
  (2, 'ENERGY EFFICIENT', 'Keep total power draw at 500W or below.', '{"maxPower":500}'::jsonb),
  (3, 'SMALL BUT MIGHTY', 'Build inside a MINI case and still score 60+.', '{"caseSize":"MINI","minScore":60}'::jsonb),
  (4, 'COMMON GROUND', 'Nothing above RARE allowed. Pure skill.', '{"maxRarity":"RARE"}'::jsonb),
  (5, 'MEMORY LANE', '64GB of RAM or more, total value under $3,500.', '{"minRamGb":64,"maxBudget":3500}'::jsonb),
  (6, 'RETRO NIGHT', 'Use the RetroBox case or the RetroTube CRT. Vibes first.', '{"requireAnyOf":["case-retrobox","mon-retrotube-17"]}'::jsonb)
)
insert into public.daily_challenges (id, title, description, rules, start_date, end_date)
select to_char(d, 'YYYY-MM-DD'), t.title, t.description, t.rules, d::date, d::date
from generate_series(date '2026-01-01', date '2028-12-31', interval '1 day') as d
join templates t on t.idx = ((d::date - date '1970-01-01') % 7)
on conflict (id) do nothing;
